# Site settings

baseurl: ""

# SEO related

title: "Hexa Programming Language"
twitter: "@hexalang"
author: "PeyTy"
description: "Hexa is a high level, strictly typed programming language that compiles to JavaScript and native apps"
image: "https://hexalang.github.io/logo.png"
url: "https://hexalang.github.io"
theme-color: "#66ccff"

# Structure

social:
  name: Hexa Programming Language
  links:
    - https://twitter.com/hexalang
    - https://github.com/hexalang

# Build settings

markdown: kramdown
highlighter: rouge
plugins:
   - jemoji
   - jekyll-seo-tag
   - jekyll-sitemap
kramdown:
  autolink: true
  input: GFM
  syntax_highlighter: rouge
