# Uploads webpack onto isekai
name: Build and deploy

on:
  push:
    branches:
      - 'kawaii'

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: '0'

            - name: Webpack
              id: build
              run: |
                cd hexalang.github.io
                mkdir -p build
                date > build/build.txt

            - name: Upload
              run: |
                    mkdir -p /tmp/build
                    cp -rf hexalang.github.io/build /tmp/build
                    git stash
                    git branch --track isekai origin/isekai && git pull --all && git fetch --all
                    git checkout isekai
                    cp -rf /tmp/build .
                    ls
                    git config user.name "GitHub Actions Bot"
                    git config user.email "<>"
                    git add .
                    git commit -m "Deploy `date`"
                    git push --set-upstream origin isekai
                    echo Poggers!
