# Uploads webpack onto isekai
name: Build and deploy

on:
  push:
    branches:
      - 'kawaii'

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: '0'

            - name: Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: yarn
                  cache-dependency-path: hexalang.github.io/yarn.lock

            - name: Webpack
              id: build
              run: |
                export -n CI # Ignore warnings
                npm install --global yarn typescript
                cd hexalang.github.io
                mkdir -p build
                yarn install --frozen-lockfile
                npx browserslist@latest --update-db
                yarn build
                node ssr.js

            - name: Upload
              run: |
                    mkdir -p /tmp/build
                    cp -rf hexalang.github.io/build/* /tmp/build
                    rm -rf hexalang.github.io/build
                    git stash
                    git branch --track isekai origin/isekai && git pull --all && git fetch --all
                    git checkout isekai
                    cp -rf /tmp/build/* .
                    git config user.name "GitHub Action"
                    git config user.email "<>"
                    date > build.txt
                    git add . # TODO -A
                    git commit -m "Deploy `date`"
                    git push --set-upstream origin isekai
                    echo Poggers!
